/**
 * Created by out_xu on 16/12/20.
 */
export const SET_HOMEPAGE_INFO= 'SET_HOMEPAGE_INFO';
export const SET_USERINFO = 'SET_USERINFO';
export const CLEAR_USERINFO = 'CLEAR_USERINFO';
export const USER_REGISTER = 'USER_REGISTER';

export const SET_PROBLEM_TABLE = 'SET_PROBLEM_TABLE';
export const SET_PROBLEM_DETAIL = 'SET_PROBLEM_DETAIL';
export const SET_PROBLEM_RESULT = 'SET_PROBLEM_RESULT';

export const SET_STATUS_TABLE = 'SET_STATUS_TABLE';


export const SET_CONTESTS_TABLE = 'SET_CONTESTS_TABLE';
export const SET_CONTEST = 'SET_CONTEST';


